use etlclass;
select * from health_care_sql;
-- 1. Retrieve the names of all patients in the database.
select name from health_care_sql;

-- 2. List the unique medical conditions present in the dataset.
select distinct(medical_condition) from health_care_sql;

-- 3. Find the total number of doctors in the healthcare system.
select count(doctor) from health_care_sql;

-- 4. Retrieve the details of all female patients.
select * from health_care_sql where gender='Female';

-- 5. what is the average age of patients in the database.
select avg(age) from health_care_sql;

-- 6. Identify the patients who have more than one medical condition.
select name,count(medical_condition) from health_care_sql group by name having count(Medical_Condition)>1;

-- 7. List the names of all doctors.
select doctor from health_care_sql;

-- 8.Identify the most common medical condition among patients.
select medical_condition,count(medical_condition) from health_care_sql group by medical_condition having count(Medical_Condition);

-- 9.Find the patients who are older than 60 years and have diabetes.
select name,age,medical_condition from health_care_sql where age>60 and medical_condition='diabetes';

-- 10.Calculate the total revenue generated by the healthcare system.
select sum(billing_amount) from health_care_sql;

-- 11.Find the doctor with the oldest patient.
select name,age,doctor from health_care_sql order by age desc limit 1;

-- 12.Calculate the average duration of medical visits.
select avg(duration) from health_care_sql;

-- 13.Give the names of patients whose name starts with A.
select name from health_care_sql where name like 'a%';

-- 14.How many male and female patients are there in dataset.
select gender,count(gender) from health_care_sql group by gender;

-- 15.how many patients are normal.
select count(name) from health_care_sql where test_results='normal';

-- 16.how many patients are abnormal or Inconclusive.
select count(name) from health_care_sql where test_results!='normal';

-- 17.how many patients of blood group AB+ are there of age above 52.
select name,blood_type,age from health_care_sql where blood_type='AB+' and age>52;

-- 18. how many patients have paid the bill above 24890.
select count(name) from health_care_sql where billing_amount>24890;

-- 19. what are the names of patients having Asthma.
select name,medical_condition from health_care_sql where medical_condition='asthma'; 

-- 20. how many patients have cancer.
select count(name) from health_care_sql where medical_condition='cancer';

-- 21. what are the names and blood groups of patients admitted to room no. 292.
select name,blood_type,room_number from health_care_sql where room_number=292;

-- 22. how many males have Arthritis.
select name,gender,medical_condition from health_care_sql where gender='male' and medical_condition='arthritis';

-- 23. How many patients were admitted to Harris and Sons hospital.
select count(name) from health_care_sql where hospital='Harris and sons';

-- 24. what are the names of patients whose Insurance Provider are Cigna.
select name,insurance_provider from health_care_sql where insurance_provider='Cigna';

-- 25. Name the Medical Condition having patients whose ages is greater than average age
select name,age,medical_condition from health_care_sql where age>(select avg(age) from health_care_sql);

